const express=require('express');const cors=require('cors');const multer=require('multer');const fs=require('fs');const path=require('path');const {spawn}=require('child_process');
const app=express();app.use(cors());app.use(express.json({limit:'2mb'}));
const ROOT=path.join(__dirname,'..');const DATA=path.join(ROOT,'data');const UP=path.join(DATA,'uploads');const OUT=path.join(DATA,'outputs');[DATA,UP,OUT].forEach(x=>fs.mkdirSync(x,{recursive:true}));
const upload=multer({dest:UP});const jobs=new Map();
function id(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function run(cmd,args){return new Promise((resolve,reject)=>{const p=spawn(cmd,args);let err='';p.stderr.on('data',d=>err+=d);p.on('close',c=>c?reject(new Error(err||'ffmpeg failed')):resolve());})}
function fallback(text){const parts=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);return parts.slice(0,12).map((t,i)=>({start:i*30,end:i*30+35,score:Math.max(55,92-i*3),emotion:i%3?'curiosity':'surprise',hook:t.replace(/^.*?\|/,'').slice(0,90),title:`Bagian menarik #${i+1}`,reason:'Punya unsur hook/curiosity dan cocok untuk Shorts.'}));}
async function analyze(text){const key=process.env.OPENAI_API_KEY;if(!key)return fallback(text);const model=process.env.OPENAI_MODEL||'gpt-5.6-luna';const prompt=`Analisis transcript berikut. Kembalikan JSON array maksimal 10 Golden Moments untuk Shorts 20-60 detik. Setiap item wajib: start(number detik), end(number), score(0-100), emotion, hook, title, reason. Prioritaskan punchline, insight, kontroversi, kejutan, problem-solution, atau kalimat yang membuat orang ingin menonton sampai selesai. Jangan membuat fakta baru. Transcript:\n${text.slice(0,50000)}`;
const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,input:prompt})});if(!r.ok)throw new Error(await r.text());const j=await r.json();let s=j.output_text||'';s=s.replace(/```json|```/g,'').trim();return JSON.parse(s);}
app.get('/api/health',(req,res)=>res.json({ok:true,version:'V7',jobs:jobs.size}));
app.post('/api/analyze',async(req,res)=>{try{const moments=await analyze(req.body.transcript||'');res.json({ok:true,moments:moments.sort((a,b)=>b.score-a.score).slice(0,10)})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/transcribe',upload.single('video'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'video required'});const wav=req.file.path+'.mp3';try{await run('ffmpeg',['-y','-i',req.file.path,'-vn','-ac','1','-ar','16000','-b:a','64k',wav]);const key=process.env.OPENAI_API_KEY;if(!key)return res.status(400).json({error:'OPENAI_API_KEY belum diisi'});const fd=new FormData();fd.append('file',new Blob([fs.readFileSync(wav)]),path.basename(wav));fd.append('model',process.env.OPENAI_TRANSCRIBE_MODEL||'gpt-4o-mini-transcribe');const r=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'transcription failed');res.json({ok:true,text:j.text});}catch(e){res.status(500).json({error:e.message})}finally{try{fs.unlinkSync(req.file.path)}catch{}try{fs.unlinkSync(wav)}catch{}}});
app.post('/api/jobs',upload.single('video'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'video required'});let clips=[];try{clips=JSON.parse(req.body.clips||'[]')}catch{}if(!clips.length)return res.status(400).json({error:'clips required'});const jobId=id();const job={id:jobId,status:'queued',progress:0,files:[],error:null,createdAt:new Date().toISOString()};jobs.set(jobId,job);res.json({ok:true,job});(async()=>{try{job.status='processing';for(let i=0;i<clips.length;i++){const c=clips[i];const start=Math.max(0,Number(c.start)||0);const end=Math.max(start+1,Number(c.end)||start+30);const duration=end-start;const out=path.join(OUT,`${jobId}_${i+1}.mp4`);await run('ffmpeg',['-y','-ss',String(start),'-i',req.file.path,'-t',String(duration),'-vf',"crop='if(gt(iw/ih,9/16),ih*9/16,iw)':'if(gt(iw/ih,9/16),ih,iw*16/9)',scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2",'-c:v','libx264','-preset','veryfast','-crf','23','-c:a','aac','-movflags','+faststart',out]);job.files.push({name:path.basename(out),url:`/files/${path.basename(out)}`,hook:c.hook||'',title:c.title||`Short #${i+1}`});job.progress=Math.round((i+1)/clips.length*100)}job.status='done';}catch(e){job.status='error';job.error=e.message}finally{try{fs.unlinkSync(req.file.path)}catch{}}})();});
app.get('/api/jobs/:id',(req,res)=>{const j=jobs.get(req.params.id);if(!j)return res.status(404).json({error:'job not found'});res.json(j)});
app.use('/files',express.static(OUT));app.use(express.static(path.join(ROOT,'web')));app.get('*',(req,res)=>res.sendFile(path.join(ROOT,'web','index.html')));
const port=process.env.PORT||3000;app.listen(port,()=>console.log(`AI Clipper V7 running on ${port}`));
